### ISSUE TITLE
AttributeError: EncodedMethod instance has no attribute 'get_information'

### ISSUE THREAD

**Issue by koto** [sfahl/mallodroid#1]
Running Mallodroid against freshly installed Androguard 1.9 - https://code.google.com/p/androguard/downloads/detail?name=androguard-1.9.tar.gz quickly produces exception: `EncodedMethod instance has no attribute 'get_information'`. In fact, looking at the androguard sources, EncodedMethod does not have `get_information` method, instead offering `EncodedMethod.get_descriptor` that lists types of parameters and type of return value.

$ ./mallodroid.py -f redacted.apk 
Analyse file: redacted.apk
Package name: redacted
App requires INTERNET permission. Continue analysis...
Traceback (most recent call last):
  File "./mallodroid.py", line 430, in <module>
    main()
  File "./mallodroid.py", line 416, in main
    _result = _check_all(_vm, _vmx, _gx)
  File "./mallodroid.py", line 188, in _check_all
    _hv, _a = _check_hostname_verifier(_method, _vm, _vmx)
  File "./mallodroid.py", line 150, in _check_hostname_verifier
    if _has_signature(_method, [_verify_string_sslsession, _verify_string_x509cert, _verify_string_sslsocket, _verify_string_subj_alt]):
  File "./mallodroid.py", line 49, in _has_signature
    _return = _method.get_information().get('return', None)
AttributeError: EncodedMethod instance has no attribute 'get_information'

**Comment by ndobri** [comment]
Instead of using the packaged release of androguard 1.9 you're better off with cloning the repo and work from there. 
`hg clone https://code.google.com/p/androguard/`
The missing method attribute is in the class EncodedMethod but that actually exists in the source: https://code.google.com/p/androguard/source/browse/androguard/core/bytecodes/dvm.py

**Comment by bowers24** [comment]
I am experiencing the same issue with androguard 1.9. When using the repo version and androguard 2.0, the INTERNET permission is not detected at all.
