### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by rafajunio** [sfahl/mallodroid#4]
Hi, 

I have a problem of encode:

App requires INTERNET permission. Continue analysis...
Traceback (most recent call last):
  File "./mallodroid.py", line 430, in <module>
    main()
  File "./mallodroid.py", line 407, in main
    _vm.create_python_export()
  File "/androguard/androguard/core/bytecodes/dvm.py", line 7890, in create_python_export
    self._create_python_export_class(_class)
  File "/androguard/androguard/core/bytecodes/dvm.py", line 7933, in _create_python_export_class
    setattr( _class, name, j )
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 17: ordinal not in range(128)

**Comment by gurol** [comment]
name variable should be encoded with UTF-8 encoding in 'setattr' function.
